import { v4 as uuid } from "uuid";

/**
 * Videos Database can be added here.
 * You can add videos of your wish with different attributes
 * */

export const videos = [
  {
    _id: uuid(),
    title: "Turks and Caicos Fly over by drone Taylor Bay 4k UHD",
    thumbnail: "/Images/Beaches/o3N54qBEzKs-HD.jpg",
    categoryName: "Beaches",
    views: "23k",
    date: "Mar 2019",
    creator: "Aaron D",
    src: "https://www.youtube.com/embed/o3N54qBEzKs?autoplay=1",
    isTrending: true,
  },
  {
    _id: uuid(),
    title: "DISCOVER ICELAND | A WINTER ROAD TRIP",
    thumbnail: "/Images/Winter/15JkSZ95wzI-SD.jpg",
    categoryName: "Winter",
    views: "490k",
    date: "Apr 2017",
    creator: "antoine janssens",
    src: "https://www.youtube.com/embed/15JkSZ95wzI?autopplay=1",
    isTrending: true,
  },
  {
    _id: uuid(),
    title: "Japan in 8K ULTRA HD - Land of The Rising Sun (60 FPS)",
    thumbnail: "/Images/Cultural/G5RpJwCJDqc-HD.jpg",
    categoryName: "Cultural",
    views: "3.2M",
    date: "Apr 2021",
    creator: "8k world",
    src: "https://www.youtube.com/embed/G5RpJwCJDqc?autopplay=1",
    isTrending: true,
  },
  {
    _id: uuid(),
    title: "Antelope Canyon, Arizona, USA [Amazing Places 4K]",
    thumbnail: "/Images/Nature/t4nM1FoUqYs-HD.jpg",
    categoryName: "Nature",
    views: "1.1M",
    date: "Oct 2016",
    creator: "Amazing Places on Our Planet",
    isTrending: true,
    src: "https://www.youtube.com/embed/t4nM1FoUqYs?autopplay=1",
  },
  {
    _id: uuid(),
    title: "Maldives 4K UHD HDR",
    thumbnail: "/Images/Winter/linlz7-Pnvw-SD.jpg",
    categoryName: "Beaches",
    views: "176k",
    date: "Feb 2022",
    creator: "Wonders Of Planet Earth 4K | 8K",
    src: "https://www.youtube.com/embed/hCQvPX0DLFM?autopplay=1",
  },

  {
    _id: uuid(),
    title: "Switzerland in 8K ULTRA HD HDR - Heaven of Earth (60 FPS)",
    thumbnail: "/Images/Winter/linlz7-Pnvw-SD.jpg",
    categoryName: "Winter",
    views: "20M",
    date: "Nov 2020",
    creator: "8k world",
    src: "https://www.youtube.com/embed/linlz7-Pnvw?autopplay=1",
  },
  {
    _id: uuid(),
    title: "360°, Angel Falls, Venezuela. Aerial 8K video",
    thumbnail: "/Images/Nature/L_tqK4eqelA-MQ.jpg",
    categoryName: "Nature",
    views: "10M",
    date: "Apr 2017",
    creator: "AirPano VR",
    src: "https://www.youtube.com/embed/L_tqK4eqelA?autopplay=1",
  },
  {
    _id: uuid(),
    title:
      "Black Sand Beach 4K (UHD) - Black Sand Beach Iceland 4K - Cinematic Travel Video",
    thumbnail: "/Images/Beaches/aH9gQ86XNK0-SD.jpg",
    categoryName: "Beaches",
    views: "1K",
    date: "Jan 2021",
    creator: "4K Video World",
    src: "https://www.youtube.com/embed/aH9gQ86XNK0?autopplay=1",
  },
  {
    _id: uuid(),
    title: "Whitehaven Beach - Whitsunday Islands - in 4k",
    thumbnail: "/Images/Beaches/YqFTAXm7_Qc-SD.jpg",
    categoryName: "Nature",
    views: "58k",
    date: "Jun 2019",
    creator: "Sailing Whitsundays",
    src: "https://www.youtube.com/embed/YqFTAXm7_Qc?autopplay=1",
  },
  {
    _id: uuid(),
    title:
      "Udaipur Tourism Guide: Things To Do In Udaipur, Best Lake Views, Hotel And Food Options | Tripoto",
    thumbnail: "/Images/Town/6oxYvj8s2Tg-HD.jpg",
    categoryName: "Town",
    views: "20k",
    date: "Feb 2022",
    creator: "Tripoto",
    src: "https://www.youtube.com/embed/6oxYvj8s2Tg?autopplay=1",
  },
  {
    _id: uuid(),
    title: "10 Top Tourist Attractions in Istanbul - Travel Video",
    thumbnail: "/Images/Town/KwmjJvM_rLs-HD.jpg",
    categoryName: "Town",
    views: "1M",
    date: "Jul 2018",
    creator: "touropia",
    src: "https://www.youtube.com/embed/KwmjJvM_rLs?autopplay=1",
  },
  {
    _id: uuid(),
    title: "Las Vegas Strip 4K City Tour [Travel Guide 2021]",
    thumbnail: "/Images/Town/_KEb4P3t9Ec-HD.jpg",
    categoryName: "Town",
    views: "1M",
    date: "Jan 2021",
    creator: "4K World",
    src: "https://www.youtube.com/embed/_KEb4P3t9Ec?autopplay=1",
  },
  {
    _id: uuid(),
    title: "10 Top Tourist Attractions in Rome - Travel Video",
    thumbnail: "/Images/Cultural/t5j2zIlbzUE-HD.jpg",
    categoryName: "Cultural",
    views: "252K",
    date: "Nov 2017",
    creator: "touropia",
    src: "https://www.youtube.com/embed/t5j2zIlbzUE?autopplay=1",
  },
  {
    _id: uuid(),
    title: "Petra, Jordan | Civilisations - BBC Two",
    thumbnail: "/Images/Cultural/SZ5JjLdzQ1o-HD.jpg",
    categoryName: "Cultural",
    views: "1M",
    date: "Mar 2018",
    creator: "BBC",
    src: "https://www.youtube.com/embed/SZ5JjLdzQ1o?autopplay=1",
  },
  {
    _id: uuid(),
    title: "The Himalayas from 20,000 ft.",
    thumbnail: "/Images/Mountains/-hTVNidxg2s-HD.jpg",
    categoryName: "Mountains",
    views: "4.6M",
    date: "Mar 2015",
    creator: "Teton Gravity Research",
    src: "https://www.youtube.com/embed/-hTVNidxg2s?autopplay=1",
  },
  {
    _id: uuid(),
    title:
      "Norway in 8K ULTRA HD HDR - Most peaceful Country in the World (60 FPS).",
    thumbnail: "/Images/Nature/eRUQPfVACs0-HD.jpg",
    categoryName: "Nature",
    views: "2M",
    date: "Feb 2021",
    creator: "Teton Gravity Research",
    src: "https://www.youtube.com/embed/eRUQPfVACs0?autopplay=1",
  },
  {
    _id: uuid(),
    title: "BEAUTY OF MANALI | manali cinematic travel video | travel india",
    thumbnail: "/Images/Mountains/nkwLjnragtw-HD.jpg",
    categoryName: "Mountains",
    views: "1M",
    date: "Mar 2019",
    creator: "roaming plus",
    src: "https://www.youtube.com/embed/nkwLjnragtw?autopplay=1",
  },
];
